### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by atanmayprdxn** [matteodelabre/mongoose-beautiful-unique-validation#35] opened 2017-06-01 06:08 UTC
I had implemented basic mongoose validation first, then switch to mongoose-beautiful-unique-validation.
This does not seem to work. I'm getting this error instead:
{
  "errors": {},
  "_message": "Validation failed",
  "name": "ValidationError"
}

Not getting errors as expected. Did I do something wrong: Following is my schema:

let collectionsSchema = new Schema({
	'eventsId': [{
		'type': Schema.Types.ObjectId,
		'ref': 'events'
	}],
	'collectionName': {
		'type': String,
		'required': true,
		'unique' : true,
		'trim' : true
	},
	'collectionSubTitle': {
		'type': String,
		'trim' : true
	},
	'collectionImage': {
		'type': String,
		'required': true
	},
	'collectionImageType': {
		'type': String,
		'enum': ['Upload', 'Url'],
		'required' : true
	},
	'showStatus': {
		'type': String,
		'enum': ['Published', 'Unpublished', 'Auto'],
		'required': true,
		'trim' : true
	}
}, {
	'timestamps': true
});

My mongoose version is : mongoose@4.10.4

**Comment by Igor-Lopes** [comment] 2017-06-01 06:14
Did you apply the plugin ?  `userSchema.plugin(beautifyUnique);`

**Comment by atanmayprdxn** [comment] 2017-06-02 12:50
@Igor-Lopes : Yes i did apply the plugin

**Comment by matteodelabre** [comment] 2017-07-09 09:33
Hello @atanmayprdxn, I cannot reproduce your bug on my machine with your version of Mongoose. I’m using MongoDB 3.4.6. Can you provide a minimal example of failing code, please?

**Comment by niftylettuce** [comment] 2017-08-07 21:34
I believe the problem is that when the hook `post('validate')` gets called, the error is not populated here - it's populated after the fact.

**Comment by niftylettuce** [comment] 2017-08-08 01:07
This can be closed @matteodelabre

**Comment by matteodelabre** [comment] 2017-08-08 01:28
I am going to close this. @atanmayprdxn, if you still encounter the problem, please feel free to re-open the issue. It would be very helpful if you provided more details about your bug, such as a minimal failing test case.

**Closed by matteodelabre** 2017-08-08 01:28 UTC
Labels: cannot reproduce
