### ISSUE TITLE
can't get it working with 4.4.12

### ISSUE THREAD

**Issue by raistlinthewiz** [matteodelabre/mongoose-beautiful-unique-validation#15] opened 2016-04-11 14:41 UTC
I'm still getting default mongoose messages;

```
{ [MongoError: E11000 duplicate key error index: buharmetre-development.users.$username_1 dup key: { : "Bonesoul" }]
  name: 'MongoError',
  message: 'E11000 duplicate key error index: buharmetre-development.users.$username_1 dup key: { : "Bonesoul" }',
  driver: true,
  code: 11000,
  index: 0,
  errmsg: 'E11000 duplicate key error index: buharmetre-development.users.$username_1 dup key: { : "Bonesoul" }',
  getOperation: [Function],
  toJSON: [Function],
  toString: [Function] }
```

and yes i've plugged it as a plugin already;

```
var beautifyUnique = require('mongoose-beautiful-unique-validation');
var UserSchema = new mongoose.Schema({
	username: { type: String, unique: true, trim: true, required: true },
	email: { type: String, unique: true, trim: true, required: true, lowercase: true }
});

UserSchema.plugin(beautifyUnique); // beatuify unique errors.
```

**Comment by matteodelabre** [comment] 2016-04-14 17:33
Hello @raistlinthewiz, which version are you using?
We have made some unpublished changes that could solve this kind of bugs, could you try using the version from GitHub directly?

**Comment by matteodelabre** [comment] 2016-05-01 15:47
Hi @raistlinthewiz, sorry to bug you with that, but can you check that this still happens with release 3.0.0 that I just published? Thank you. :)

**Comment by matteodelabre** [comment] 2016-06-27 16:42
Hi @raistlinthewiz, I'm closing this issue as I can't reproduce and I don't have any feedback. Please feel free to leave a comment if you want it re-opened. :)

**Closed by matteodelabre** 2016-06-27 16:42 UTC
